# [env]
# CARGO_TARGET_DIR = "target"

[settings]
env_file = ".env"
idiomatic_version_file_enable_tools = ["node"]
experimental = true

[tools]
# go = "1.22"
# java = "21"
node = "20.0"
python = "3.10"
# rust = "1.81"
uv = "0.7"
# erlang = "27.0"
# elixir = "1.17.0"
